controller_list:
  - name: arm/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      #- arm_big_finger_left_join
      #- arm_small_finger_left_join
      #- arm_big_finger_right_join
      #- arm_small_finger_right_join
  #- name: gripper/joint_trajectory_controller
    #action_ns: follow_joint_trajectory
    #type: FollowJointTrajectory
    #joints:
      #- gripper_big_finger_left_join
      #- gripper_big_finger_right_join
      #- gripper_small_finger_left_join
      #- gripper_small_finger_right_join
