joint_names: ['arm_can0_joint_1','arm_can0_joint_2']

action_name: /arm_can0/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm_can0/driver
default_vel: 0.06 #0.50 #0.50 => simulation env, 0.06 => real robot env
default_acc: 0.01 #0.10 #0.10 => simulation env, 0.01 => real robot env

# back side positions
home: [[0.0, 0.0]]
grasp: [[0.4999994350583229, 1.15975]]

