## joint_names
joint_names: [arm_can0_joint_1,arm_can0_joint_2]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - arm_can0_joint_1
     - arm_can0_joint_2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_can0_joint_1: {trajectory: 0.1, goal: 0.1}
      arm_can0_joint_2: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7


## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - arm_can0_joint_1
    - arm_can0_joint_2
  required_drive_mode: 1

arm_can0_joint_1_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_can0_joint_1
  required_drive_mode: 1
arm_can0_joint_2_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_can0_joint_2
  required_drive_mode: 1

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - arm_can0_joint_1
    - arm_can0_joint_2
  required_drive_mode: 2

arm_can0_joint_1_velocity_controller:
  type: position_controllers/JointPositionController
  joint: arm_can0_joint_1
  required_drive_mode: 2
arm_can0_joint_2_velocity_controller:
  type: position_controllers/JointPositionController
  joint: arm_can0_joint_2
  required_drive_mode: 2

