controller_list:
  - name: arm_can0/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - arm_can0_joint_1
      - arm_can0_joint_2
  - name: arm_can1/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - arm_can1_joint_3
      - arm_can1_joint_4


